### ISSUE TITLE
Handling percolate results

### ISSUE THREAD

**Issue by ghost** [consulthys/logstash-filter-percolate#1]
This functionality is great, but is there a way to use this plug in to percolate documents and then run a script to deal with the results?

**Comment by consulthys** [comment]
You can probably use scripted updates with the  `elasticsearch` output once you know which queries match your percolated documents. Maybe you can expand a little bit and describe what you're trying to achieve.

**Comment by ghost** [comment]
Hi, thanks for getting back to me so quickly.

I have a stream of data being inserted into an elastic search cluster with
logstash. I would like to use the percolate function to check each record
against a set of stored queries and trigger action (for example an email
being sent detailing the results) before/as it is stored in the cluster.

Is this possible? And is this tool the correct tool for this job?

Thanks,
Tom.

**Comment by consulthys** [comment]
Yes, it's definitely possible. I'm using this filter to send alerts when documents are being indexed/updated into my cluster, so that definitely sounds like a similar use case to yours.

Basically, this filter will store the IDs of the matching queries in a new field of your choice. Downstream (i.e. another filter or in the outputs), you can check if this new field exists and if yes, you can act upon the matching query IDs and do whatever you need to, i.e. send emails, call webhooks, etc

**Comment by ghost** [comment]
ok thats great to hear.

how do I specify a field to added if a certain query is matched? does that
occur in the logstash .conf file inside the percolate {} clause?

**Comment by consulthys** [comment]
You can see how it's configured [here](https://github.com/consulthys/logstash-filter-percolate#using-this-plugin)

**Comment by ghost** [comment]
thankyou,

whereabouts does the percolate {} part go? after the input part?

**Comment by consulthys** [comment]
That's a filter, it goes inside the [`filter {}` section](https://www.elastic.co/guide/en/logstash/current/advanced-pipeline.html)

**Comment by ghost** [comment]
ok this all sounds great.

so if i inserted:

percolate {
        hosts => ["192.168.253.253:9200","192.168.253.251:9200","
192.168.253.250:9200","192.168.253.249:9200",        "192.168.253.248:9200
","192.168.253.244:9200"]
        index => "toms_index"
        type => "toms_data_type"
        id => "percolation_match"
    }

into my filter bracket, that will percolate all records headed for the
specified index and add a field called "percolation_match" with the
percolate query IDs as the field value.

is that correct?

thanks, for your continued assistance

Tom.

**Comment by consulthys** [comment]
```
        id => "percolation_match"
```

should be

```
        target => "percolation_match"
```

`id` is only necessary if you want to percolate an existing document.
